In [ ]:
import pandas as pd
import numpy as np

from datetime import datetime

In [ ]:
df = pd.read_csv("iot_telemetry_data.csv")
df.head()

,ts,device,co,humidity,light,lpg,motion,smoke,temp
0,1.594512e+09,b8:27:eb:bf:9d:51,0.004956,51.000000,False,0.007651,False,0.020411,22.700000
1,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
2,1.594512e+09,b8:27:eb:bf:9d:51,0.004976,50.900000,False,0.007673,False,0.020475,22.600000
3,1.594512e+09,1c:bf:ce:15:ec:4d,0.004403,76.800003,True,0.007023,False,0.018628,27.000000
4,1.594512e+09,b8:27:eb:bf:9d:51,0.004967,50.900000,False,0.007664,False,0.020448,22.600000

In [ ]:
group = df.groupby("device")
for device, data in group:
    print(device,data , sep="\n")

00:0f:00:70:91:0a
                  ts             device        co   humidity  light       lpg  \
1       1.594512e+09  00:0f:00:70:91:0a  0.002840  76.000000  False  0.005114
7       1.594512e+09  00:0f:00:70:91:0a  0.002938  76.000000  False  0.005241
15      1.594512e+09  00:0f:00:70:91:0a  0.002905  75.800003  False  0.005199
20      1.594512e+09  00:0f:00:70:91:0a  0.002938  75.800003  False  0.005241
23      1.594512e+09  00:0f:00:70:91:0a  0.002840  76.000000  False  0.005114
...              ...                ...       ...        ...    ...       ...
405169  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247
405172  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.400002  False  0.006247
405175  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.400002  False  0.006247
405179  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247
405182  1.595203e+09  00:0f:00:70:91:0a  0.003745  75.300003  False  0.006247

        motion     smoke       temp
1        False  0.013275  19.700001
7        False  0.013628  19.700001
15       False  0.013509  19.700001
20       False  0.013628  19.700001
23       False  0.013275  19.700001
...        ...       ...        ...
405169   False  0.016437  19.200001
405172   False  0.016437  19.200001
405175   False  0.016437  19.200001
405179   False  0.016437  19.200001
405182   False  0.016437  19.200001

[111815 rows x 9 columns]
1c:bf:ce:15:ec:4d
                  ts             device        co   humidity  light       lpg  \
3       1.594512e+09  1c:bf:ce:15:ec:4d  0.004403  76.800003   True  0.007023
5       1.594512e+09  1c:bf:ce:15:ec:4d  0.004391  77.900002   True  0.007009
8       1.594512e+09  1c:bf:ce:15:ec:4d  0.004345  77.900002   True  0.006957
11      1.594512e+09  1c:bf:ce:15:ec:4d  0.004383  78.000000   True  0.007000
13      1.594512e+09  1c:bf:ce:15:ec:4d  0.004451  78.000000   True  0.007079
...              ...                ...       ...        ...    ...       ...
405165  1.595203e+09  1c:bf:ce:15:ec:4d  0.004524  75.900002   True  0.007162
405171  1.595203e+09  1c:bf:ce:15:ec:4d  0.004532  75.900002   True  0.007172
405174  1.595203e+09  1c:bf:ce:15:ec:4d  0.004532  75.900002   True  0.007172
405178  1.595203e+09  1c:bf:ce:15:ec:4d  0.004553  75.800003   True  0.007196
405181  1.595203e+09  1c:bf:ce:15:ec:4d  0.004540  75.699997   True  0.007181

        motion     smoke  temp
3        False  0.018628  27.0
5        False  0.018589  27.0
8        False  0.018440  27.0
11       False  0.018563  27.0
13       False  0.018786  27.0
...        ...       ...   ...
405165   False  0.019021  26.6
405171   False  0.019049  26.6
405174   False  0.019049  26.6
405178   False  0.019117  26.6
405181   False  0.019076  26.6

[105918 rows x 9 columns]
b8:27:eb:bf:9d:51
                  ts             device        co  humidity  light       lpg  \
0       1.594512e+09  b8:27:eb:bf:9d:51  0.004956      51.0  False  0.007651
2       1.594512e+09  b8:27:eb:bf:9d:51  0.004976      50.9  False  0.007673
4       1.594512e+09  b8:27:eb:bf:9d:51  0.004967      50.9  False  0.007664
6       1.594512e+09  b8:27:eb:bf:9d:51  0.004976      50.9  False  0.007673
9       1.594512e+09  b8:27:eb:bf:9d:51  0.004970      50.9  False  0.007667
...              ...                ...       ...       ...    ...       ...
405173  1.595203e+09  b8:27:eb:bf:9d:51  0.005901      48.4  False  0.008681
405176  1.595203e+09  b8:27:eb:bf:9d:51  0.005909      48.4  False  0.008689
405177  1.595203e+09  b8:27:eb:bf:9d:51  0.005877      48.5  False  0.008654
405180  1.595203e+09  b8:27:eb:bf:9d:51  0.005882      48.5  False  0.008660
405183  1.595203e+09  b8:27:eb:bf:9d:51  0.005914      48.4  False  0.008695

        motion     smoke  temp
0        False  0.020411  22.7
2        False  0.020475  22.6
4        False  0.020448  22.6
6        False  0.020475  22.6
9        False  0.020457  22.6
...        ...       ...   ...
405173   False  0.023359  22.3
405176   False  0.023382  22.3
405177   False  0.023284  22.3
405180   False  0.023301  22.2
405183   False  0.023400  22.2

[187451 rows x 9 columns]

In [ ]:
device_1 = group.get_group("00:0f:00:70:91:0a")
device_1

,ts,device,co,humidity,light,lpg,motion,smoke,temp
1,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
7,1.594512e+09,00:0f:00:70:91:0a,0.002938,76.000000,False,0.005241,False,0.013628,19.700001
15,1.594512e+09,00:0f:00:70:91:0a,0.002905,75.800003,False,0.005199,False,0.013509,19.700001
20,1.594512e+09,00:0f:00:70:91:0a,0.002938,75.800003,False,0.005241,False,0.013628,19.700001
23,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
...,...,...,...,...,...,...,...,...,...
405169,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.300003,False,0.006247,False,0.016437,19.200001
405172,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.400002,False,0.006247,False,0.016437,19.200001
405175,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.400002,False,0.006247,False,0.016437,19.200001
405179,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.300003,False,0.006247,False,0.016437,19.200001
405182,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.300003,False,0.006247,False,0.016437,19.200001

In [ ]:
device_1["Datetime"] = pd.to_datetime(device_1['ts'],unit='s')
device_1

<ipython-input-7-29e0222de50f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  device_1["Datetime"] = pd.to_datetime(device_1['ts'],unit='s')

,ts,device,co,humidity,light,lpg,motion,smoke,temp,Datetime
1,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001,2020-07-12 00:01:34.735567616
7,1.594512e+09,00:0f:00:70:91:0a,0.002938,76.000000,False,0.005241,False,0.013628,19.700001,2020-07-12 00:01:46.869075968
15,1.594512e+09,00:0f:00:70:91:0a,0.002905,75.800003,False,0.005199,False,0.013509,19.700001,2020-07-12 00:02:02.785731840
20,1.594512e+09,00:0f:00:70:91:0a,0.002938,75.800003,False,0.005241,False,0.013628,19.700001,2020-07-12 00:02:11.476376320
23,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001,2020-07-12 00:02:15.289086464
...,...,...,...,...,...,...,...,...,...,...
405169,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.300003,False,0.006247,False,0.016437,19.200001,2020-07-20 00:03:16.329781760
405172,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.400002,False,0.006247,False,0.016437,19.200001,2020-07-20 00:03:20.684223232
405175,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.400002,False,0.006247,False,0.016437,19.200001,2020-07-20 00:03:25.039889920
405179,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.300003,False,0.006247,False,0.016437,19.200001,2020-07-20 00:03:33.162014976
405182,1.595203e+09,00:0f:00:70:91:0a,0.003745,75.300003,False,0.006247,False,0.016437,19.200001,2020-07-20 00:03:36.979521536

In [ ]:
device_1.set_index("Datetime", inplace=True)

In [ ]:
s = device_1.resample("Min").mean()
s

,ts,co,humidity,light,lpg,motion,smoke,temp
Datetime,,,,,,,,
2020-07-12 00:01:00,1.594512e+09,0.002889,76.000000,0.0,0.005178,0.0,0.013451,19.700001
2020-07-12 00:02:00,1.594512e+09,0.002880,75.933334,0.0,0.005166,0.0,0.013418,19.744445
2020-07-12 00:03:00,1.594512e+09,0.002867,76.063635,0.0,0.005150,0.0,0.013373,19.763636
2020-07-12 00:04:00,1.594512e+09,0.002838,76.091665,0.0,0.005111,0.0,0.013266,19.750000
2020-07-12 00:05:00,1.594512e+09,0.002851,76.288888,0.0,0.005128,0.0,0.013314,19.744445
...,...,...,...,...,...,...,...,...
2020-07-19 23:59:00,1.595203e+09,0.003745,70.479999,0.0,0.006247,0.0,0.016437,16.739999
2020-07-20 00:00:00,1.595203e+09,0.003743,75.500000,0.0,0.006245,0.0,0.016432,19.299999
2020-07-20 00:01:00,1.595203e+09,0.003747,75.370002,0.0,0.006250,0.0,0.016445,19.299999
2020-07-20 00:02:00,1.595203e+09,0.003747,75.383335,0.0,0.006250,0.0,0.016446,19.266666
2020-07-20 00:03:00,1.595203e+09,0.003749,75.342860,0.0,0.006253,0.0,0.016453,19.200001

In [ ]:
s.to_csv("data_device1.csv")